name: Setup SQL Server Database

on: workflow_dispatch

jobs:
  Deploy-Development:
    uses: ./.github/workflows/sql-deploy.yml
    with:
      environment: 'Development'
      server-secret: 'SQL_SERVER'
      user-secret: 'SQL_USER'
      password-secret: 'SQL_PASSWORD'

  Deploy-Production:
    needs: Deploy-Development
    uses: ./.github/workflows/sql-deploy.yml
    with:
      environment: 'Production'
      server-secret: 'AP_SQL_SERVER'
      user-secret: 'AP_SQL_USER'
      password-secret: 'AP_SQL_PASSWORD'
