name: Set up SQL Server

on:
  workflow_dispatch:

jobs:
  DeployDevelopment:
    uses: ./.github/workflows/createDBTemplate.yml
    with:
      Job_type: "Development"
    secrets:
      SQL_server: ${{ secrets.SQL_SERVER }}
      SQL_user: ${{ secrets.SQL_USER }}
      SQL_password: ${{ secrets.SQL_PASSWORD }}


  production:
    needs: DeployDevelopment
    uses: ./.github/workflows/createDBTemplate.yml
    with:
      Job_type: "Production"
    secrets:
      SQL_server: ${{ secrets.AP_SQL_SERVER }}
      SQL_user: ${{ secrets.AP_SQL_USER }}
      SQL_password: ${{ secrets.AP_SQL_PASSWORD }}

