name: Deploy SQL Database

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install SQLCMD
      run: sudo apt-get install -y mssql-tools unixodbc-dev

    - name: Run SQL Script on Remote SQL Server
      env:
        SQL_SERVER: ${{ secrets.SQL_SERVER }}
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      run: |
        sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -i sql_setup.sql
