name: Setup SQL Server Database
on: 
  workflow_dispatch

jobs:
  Deploy-Development:
    uses: ./.github/workflows/createDBTemplate.yml  # ✅ Correct way to call reusable workflows
    with:
      Job_type: "Development"  # Must match the required input name in the reusable workflow
    secrets:
      SQL_server: ${{ secrets.SQL_SERVER }}
      SQL_user: ${{ secrets.SQL_USER }}
      SQL_password: ${{ secrets.SQL_PASSWORD }}

  Deploy-Production:
    needs: Deploy-Development  # Ensures this runs only after Deploy-Development completes
    uses: ./.github/workflows/createDBTemplate.yml
    with:
      Job_type: "Production"
    secrets:
      SQL_server: ${{ secrets.AP_SQL_SERVER }}
      SQL_user: ${{ secrets.AP_SQL_USER }}
      SQL_password: ${{ secrets.AP_SQL_PASSWORD }}
