name: Setup SQL Server Database
on: push
jobs:
  setup-database:
    runs-on: ubuntu-latest  # Base runner to support Docker
    container:
      image: mcr.microsoft.com/windows/servercore:ltsc2022  # Windows-based container
      options: --user ContainerAdministrator  # Required for admin privileges in Windows containers
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install sqlcmd in the Windows container
      - name: Install sqlcmd
        run: |
          where sqlcmd || (
            echo "Installing sqlcmd..."
            curl -o msodbcsql.msi https://go.microsoft.com/fwlink/?linkid=2230310
            msiexec /i msodbcsql.msi /quiet /qn /norestart IACCEPTMSODBCSSQLLICENSETERMS=YES
            set "PATH=%PATH%;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn"
          )
        shell: cmd

      # Execute SQL scripts using the pre-provided Pinggy URL
      - name: Create Database
        run: |
          sqlcmd -S "${{ secrets.SQL_SERVER }}" -U Auto_user -P ${{ secrets.SQL_PASSWORD }} -i DatabaseAdministration/DBAutomation/sql_setup.sql
        shell: cmd
