name: Deploy SSIS Package

on:
  workflow_call:
    inputs:
      sql_server:
        required: true
        type: string
      sql_user:
        required: true
        type: string
      sql_password:
        required: true
        type: string

jobs:
  deploy-ssis:
    runs-on: self-hosted  # Windows runner with SSIS tools
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSIS Catalog Folder
        shell: powershell
        run: |
          $sqlcmd = "IF NOT EXISTS(SELECT 1 FROM [SSISDB].[catalog].[folders] WHERE name = 'SSISMigrationProject') `
                    BEGIN EXEC [SSISDB].[catalog].[create_folder] @folder_name = 'SSISMigrationProject', @folder_id = NULL END"
          sqlcmd -S "${{ inputs.sql_server }}" -U "${{ inputs.sql_user }}" -P "${{ inputs.sql_password }}" -Q "$sqlcmd"

      - name: Deploy SSIS Project
        shell: powershell
        run: |
          $ispacPath = "HandsOnProject/Timesheet/YourSSISProject.ispac"
          $deployCmd = "[SSISDB].[catalog].[deploy_project] `
              @folder_name = 'MySSISFolder', `
              @project_name = 'SSIS_Project', `
              @project_stream = $(Get-Content -Path $ispacPath -Encoding Byte -Raw | ForEach-Object{[System.BitConverter]::ToString($_)})"
          
          sqlcmd -S "${{ inputs.sql_server }}" -U "${{ inputs.sql_user }}" -P "${{ inputs.sql_password }}" -Q "$deployCmd"
