name: SSIS Migration Database Creation

on:
  workflow_call:
  
jobs:
  Create-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo "/opt/mssql-tools/bin" >> $GITHUB_PATH

      - name: Run SQL Automation
        run: |
          sqlcmd -S "${{ secrets.SQL_server }}" -U "${{ secrets.SQL_user }}" -P "${{ secrets.SQL_password }}" -i HandsOnProject/Timesheet/CreateDatabaseAndTable.sql
