name: SQL Linting & Syntax Check

on:
  push:
    paths:
      - '**/*.sql'
  pull_request:
    paths:
      - '**/*.sql'

jobs:
  lint-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history is available

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Get Modified SQL Files
        id: modified-files
        run: |
          modified_sql_files=$(git diff --name-only HEAD~1 HEAD -- '*.sql')
          if [[ -n "$modified_sql_files" ]]; then
            echo "Modified SQL files detected:"
            echo "$modified_sql_files"
            echo "FILES=$modified_sql_files" >> $GITHUB_ENV
          else
            echo "No modified SQL files found."
            echo "FILES=" >> $GITHUB_ENV
          fi

      - name: Lint Modified SQL Files
        if: env.FILES != ''
        run: |
          echo "Linting modified SQL files..."
          sqlfluff lint --dialect mysql $FILES || exit 1

      - name: Parse Modified SQL Files
        if: env.FILES != ''
        run: |
          echo "Checking SQL syntax of modified files..."
          sqlfluff parse --dialect mysql $FILES




