name: SQL Syntax Check

on:
  push:
    paths:
      - '**.sql'
  pull_request:
    paths:
      - '**.sql'

jobs:
  check-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start MySQL
        run: |
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root -d mysql:latest
          sleep 10  # Wait for MySQL to start

      - name: Validate SQL scripts
        run: |
          for file in $(find . -name "*.sql"); do
            echo "Checking $file"
            docker exec -i mysql-container mysql -uroot -proot -e "source $file"
          done

      - name: Stop MySQL
        if: always()
        run: docker stop mysql-container
