name: Notify Teams on Merge

on:
  pull_request:
    types:
      - closed  # Runs only when a PR is merged or closed

jobs:
  notify-teams:
    if: github.event.pull_request.merged == true  # Run only if PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Microsoft Teams
        env:
          WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          JSON_PAYLOAD=$(jq -n --arg repo "${{ github.repository }}" \
            --arg title "${{ github.event.pull_request.title }}" \
            --arg merged_by "${{ github.actor }}" \
            --arg url "${{ github.event.pull_request.html_url }}" \
            '{ text: " *Pull Request Merged!* 🎉\n\n *Repository:* \($repo)\n *PR Title:* \($title)\n *Merged by:* \($merged_by)\n🔗 [View Pull Request](\($url))" }')

          curl -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$WEBHOOK_URL"


